---
title: "Premier League 2019/20 season analysis"
output:
  pdf_document: default
  pdf document: default
---

## This is a document for analyzing the Premier League seasonal performance of players and teams

### Loading Required Packages

```{r, packages}
library(tidyverse)
library(gridExtra)
```

### Loading Required Datasets

```{r, load-data}
table <- read.csv("~/DataBEL/Premier League 2019_20 Table.csv")
assists <- read.csv("~/DataBEL/Premier League 2019_20 Assists.csv",
                    encoding = "UTF-8")
goals <- read.csv("~/DataBEL/Premier League 2019_20 Goal Scored.csv", 
                  encoding = "UTF-8")
clean_sheets <- read.csv("~/DataBEL/Premier League 2019_20 Clean Sheets.csv",
                         encoding = "UTF-8")
```

### Column names of the datasets

```{r, col-names}
colnames(table)
colnames(assists)
colnames(goals)
colnames(clean_sheets)
```

### The Final Premier League 2019/20 Table

```{r, table}
pdf("PL-table.pdf", height=11, width=8.5)
grid.table(table)
dev.off()
knitr::kable(table, caption = "Premier League 2019/20 season")
```

### Biggest Winners vs Biggest Losers

```{r, win-vs-lose, fig.width = 9, fig.height = 9}
table %>% 
  arrange(desc(Won)) %>%
  ggplot(aes(reorder(Team.Name, Won), Won, fill = Team.Name)) +
  geom_bar(stat = "identity", color = "black") +
  labs(title = "Liverpool can't stop winning", 
       y = "Games Won", x = "Team Name") +
  coord_flip() +
  theme_classic()
ggsave("table-won.png")
table %>% 
  arrange(desc(Lost)) %>%
  ggplot(aes(reorder(Team.Name, Lost), Lost, fill = Team.Name)) +
  geom_bar(stat = "identity", color = "black") +
  labs(title = "Norwich loses a lot", 
       y = "Games Lost", x = "Team Name") +
  coord_flip() +
  theme_classic()
ggsave("table-lost.png")

```

### Who Shared the Most Points?

```{r, draw, fig.width = 9,fig.height = 9}
table %>% 
  arrange(desc(Drawn)) %>%
  ggplot(aes(reorder(Team.Name, Drawn), Drawn, fill = Team.Name)) +
  geom_bar(stat = "identity", color = "black") +
  labs(title = "Sharing is Caring", 
       y = "Games Drawn", x = "Team Name") +
  coord_flip() +
  theme_classic()
ggsave("table-drawn.png")
```

### Goals Scored vs Goals Conceded

```{r, gs-vs-gc, fig.width = 9, fig.height = 9}
table %>% 
  arrange(desc(GF)) %>%
  ggplot(aes(reorder(Team.Name, GF), GF, fill = Team.Name)) +
  geom_bar(stat = "identity", color = "black") +
  labs(title = "Manchester City scored the most", 
       y = "Games Won", x = "Team Name") +
  coord_flip() +
  theme_classic()
ggsave("goals-scored.png")
table %>% 
  arrange(desc(GA)) %>%
  ggplot(aes(reorder(Team.Name, GA), GA, fill = Team.Name)) +
  geom_bar(stat = "identity", color = "black") +
  labs(title = "Norwich City left their net open",
       y = "Games Lost", x = "Team Name") +
  coord_flip() +
  theme_classic()
ggsave("goals-conceded.png")
```

### Highest Goal Scorers

```{r, top-gs, fig.width = 9, fig.height = 9}
goals %>% 
  arrange(desc(goals_scored)) %>% 
  ggplot(aes(reorder(Player, goals_scored), goals_scored, fill = Player)) +
  geom_bar(stat = "identity", color = "black") +
  labs(title = "Jamie Vardy -- Chat S***, Get Banged",
       y = "Goals Scored", x = "Player Name") +
  coord_flip()
ggsave("goal-scorers.png")
```

### Top Playmakers

```{r, assists, fig.width= 9, fig.height= 9}
assists %>% 
  arrange(desc(Assists)) %>% 
  ggplot(aes(reorder(Player, Assists), Assists, fill = Player)) +
  geom_bar(stat = "identity", color = "black") +
  labs(title = "De Bruyne is a Play-magician",
       y = "Assists", x = "Player Name") +
  coord_flip()
ggsave("assists.png")
```

### Most Clean Sheets

```{r, clean-sheets, fig.width = 9, fig.height = 9}
clean_sheets %>% 
  arrange(desc(clean_sheets)) %>% 
  ggplot(aes(reorder(Player, clean_sheets), clean_sheets, fill = Player)) +
  geom_bar(stat = "identity", color = "black") +
  labs(title = "Ederson's gloves are so clean",
       y = "Clean Sheets", x = "Player Name") +
  coord_flip()
ggsave("clean-sheets.png")
```

